# Generated by Django 6.1.1 on 2026-10-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_insta", "0003_photo_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
