# Generated by Django 6.1.1 on 2026-10-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="image_url",
        ),
        migrations.AddField(
            model_name="article",
            name="image_file",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
